    name: Deploy
    on:
      push:
        branches:
          - master
     
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          - run: docker build -t fujayelk/docker-react -f Dockerfile.dev .
          - run: docker run -e CI=true fujayelk/docker-react npm run test
     
          - name: Generate deployment package
            run: zip -r deploy.zip . -x '*.git*'
     
          - name: Deploy to EB
            uses: einaregilsson/beanstalk-deploy@v18
            with:
              aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
              aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
              application_name: docker-react
              environment_name: docker-react-env
              existing_bucket_name: elasticbeanstalk-eu-north-1-699083849445
              region: eu-north-1
              version_label: ${{ github.sha }}
              deployment_package: deploy.zip